### ISSUE TITLE
Missing json dependency?!

### ISSUE THREAD

**Issue by blueyed** [alexgenco/neovim-ruby#46]
It seems like with Neovim master "json" is required?!

Not sure, but I've noticed this with https://github.com/tweekmonster/vim-testbed - and have not really investigated yet.

```
+docker run -a stderr --rm -v /home/travis/build/tweekmonster/vim-testbed/example:/testplugin -v /tmp/tmp.MbsDtSmQ3M:/home/vimtest -v /home/travis/build/tweekmonster/vim-testbed/example/test/plugins:/home/vimtest/plugins vim-testbed-example neovim-master --headless -u NONE '+ruby open('\''/home/vimtest/ruby'\'', '\''w'\'') { |f| f << '\''ruby was here'\'' }' +q
function provider#ruby#Call[8]..remote#host#Require[10]..provider#ruby#Require, line 10
Vim(if):ch 1 was closed by the client
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/gems/2.4.0/gems/neovim-0.6.0/lib/neovim/logging.rb:2:in `<top (required)>'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/gems/2.4.0/gems/neovim-0.6.0/lib/neovim/session.rb:1:in `<top (required)>'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/gems/2.4.0/gems/neovim-0.6.0/lib/neovim/client.rb:3:in `<top (required)>'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/gems/2.4.0/gems/neovim-0.6.0/lib/neovim.rb:1:in `<top (required)>'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/gems/2.4.0/gems/neovim-0.6.0/lib/neovim/host.rb:1:in `<top (required)>'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
^Ifrom /usr/lib/ruby/gems/2.4.0/gems/neovim-0.6.0/bin/neovim-ruby-host:3:in `<top (required)>'
^Ifrom /usr/bin/neovim-ruby-host:23:in `load'
^Ifrom /usr/bin/neovim-ruby-host:23:in `<main>'
Failed to load ruby host. You can try to see what happened by starting nvim with $NVIM_RUBY_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages./bin/bash: line 30: /tmp/tmp.MbsDtSmQ3M/ruby: No such file or directory
+'[' '' '!=' 'ruby was here' ']'
+echo 'Failed to get output from Ruby for neovim-master --headless.'
Failed to get output from Ruby for neovim-master --headless.
```

**Comment by blueyed** [comment]
Installing the Alpine `ruby-json` fixed it.

Feel free to close this issue.

**Comment by alexgenco** [comment]
Hmm yeah I just added this dependency, that's weird that it's failing on ruby 2.4.0, since it should be part of the stdlib: http://ruby-doc.org/stdlib-2.4.0/libdoc/json/rdoc/JSON.html.

I'll patch this and push a new gem shortly. Sorry about that.

**Comment by blueyed** [comment]
No problem.  It might be something special about Alpine Linux, where this is a separate package for space reasons etc.

Just having the dependency would have failed, too - since it likely requires additional headers then to build it.

**Comment by alexgenco** [comment]
Can you give it another try with the latest release (0.6.1)? It uses `multi_json` instead of a hard json dependency, and only loads it when logging is enabled.

**Comment by blueyed** [comment]
Thanks!
Trying in https://github.com/tweekmonster/vim-testbed/pull/52.

**Comment by blueyed** [comment]
Thanks for the quick fix!
